apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: facedetection
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
      - name: facedetection
        image: docker.io/andersonandrei/functionbench-knative:facedetection
        resources:  
          requests:
            cpu: 1
            memory: 1024M
          limits:
            cpu: 1
            memory: 1024M               