apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml_video_face_detection
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - name: facedetection
          image: registry.gitlab.inria.fr/naleblon/knative-functions/functionbench-knative:facedetection
