apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: videoprocessing
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
      - name: videoprocessing
        image: docker.io/andersonandrei/functionbench-knative:videoprocessing
        resources:  
          requests:
            cpu: 1
            memory: 1024M
          limits:
            cpu: 1
            memory: 1024M               