apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video_processing
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - name: videoprocessing
          image: registry.gitlab.inria.fr/naleblon/knative-functions/functionbench-knative:videoprocessing
          imagePullPolicy: Always
