apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: facedetection-warm
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - name: facedetection
          image: registry.gitlab.inria.fr/naleblon/knative-functions/functionbench-knative:facedetection
