apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pyaes
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - name: pyaes
          image: registry.gitlab.inria.fr/naleblon/knative-functions/functionbench-knative:pyaes
